config/routes.rb
Rails.application.routes.draw do
    root "sessions#new"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"

    resources :users, only: %i(show edit update) do
        post "demo"
        post "hidedemo"

        resources :tournaments, only: %i(index show edit update) do
            get "refresh", to: "tournaments#refresh_all", on: :collection
            get "refresh", on: :member
            post "finalize", on: :member

            resources :matches, only: :update do
                post "switch", on: :member
                post "start", on: :member
            end
        end
    end

    get "view/:id", to: "tournament_viewer#view", as: :view_tournament
    get "view/:id/gold", to: "tournament_viewer#gold", as: :view_tournament_gold
    get "view/:id/blue", to: "tournament_viewer#blue", as: :view_tournament_blue
    get "view/:id/gold_score", to: "tournament_viewer#gold_score", as: :view_tournament_gold_score
    get "view/:id/blue_score", to: "tournament_viewer#blue_score", as: :view_tournament_blue_score
    get "view/:id/on_deck_gold", to: "tournament_viewer#on_deck_gold", as: :view_tournament_on_deck_gold
    get "view/:id/on_deck_blue", to: "tournament_viewer#on_deck_blue", as: :view_tournament_on_deck_blue

    get "kiosk/:id", to: "kiosk#show", as: :tournament_kiosk

    get "/routes", to: redirect("/rails/info/routes") if Rails.env.development?
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
    include ApplicationHelper
    include ChallongeHelper

    belongs_to :user
    has_many :teams, dependent: :destroy
    has_many :matches, dependent: :destroy

    validates :challonge_id, numericality: { only_integer: true, greater_than: 0 },
                             uniqueness: { scope: :user_id }
    validates :name, presence: true
    validates :challonge_alphanumeric_id, presence: true, format: { with: /\A\w+\z/ },
                                          uniqueness: { scope: :user_id, case_sensitive: false }
    validates :state, presence: true
    validates :progress_meter, numericality: { only_integer: true, greater_than_or_equal_to: 0,
                                               less_than_or_equal_to: 100 }
    validates :challonge_url, presence: true,
                              uniqueness: { scope: :user_id, case_sensitive: false }
    validates :tournament_type, presence: true
    validates :subdomain, format: { with: /\A[a-zA-Z0-9-]+\z/ }, allow_blank: true
    validates :view_gold_score, numericality: { only_integer: true,
                                                greater_than_or_equal_to: 0 }
    validates :view_blue_score, numericality: { only_integer: true,
                                                greater_than_or_equal_to: 0 }
    validates :slack_notifications_channel, presence: true, if: :send_slack_notifications
    validate :validate_datetimes

    scope :underway, -> { where(state: Tournament.states_to_show) }
    scope :complete, -> { where(state: "complete") }

    # We show a tournament in the tournaments/index view only if its state is
    # one of these values.
    def self.states_to_show
        return %w(underway group_stages_underway group_stages_finalized
                  awaiting_review).freeze
    end

    def self.show_state?(state)
        return states_to_show.include?(state)
    end

    # Tests if this Tournament is complete.
    def complete?
        return state == "complete"
    end

    # Tests if this Tournament can be finalized.
    def finalizable?
        return state == "awaiting_review"
    end

    # Tests whether this Tournament is in the first stage of a two-stage tournament.
    def in_group_stage?
        return state == "group_stages_underway" || state == "group_stages_finalized"
    end

    def update!(obj)
        self.description = obj.description
        self.name = obj.name
        self.challonge_alphanumeric_id = obj.url
        self.state = obj.state
        self.progress_meter = obj.progress_meter
        self.challonge_url = obj.full_challonge_url
        self.tournament_type = obj.tournament_type
        self.started_at = obj.started_at
        self.subdomain = obj.subdomain
        self.gold_on_left ||= Rails.configuration.gold_on_left_default
        save!
    end

    # On success, returns a `tournament` object that contains the properties of
    # this tournament. The caller can also request the teams and matches in
    # the tournament.
    # On failure, returns an `error` object that describes the error.
    def get_info(get_teams:, get_matches:)
        return get_tournament_info(self, get_teams: get_teams, get_matches: get_matches)
    end

    # Finalizes this tournament.  All matches in the tournament must be complete
    # for this call to succeed.
    # On success, returns a `tournament` object that contains the properties of
    # the tournament.
    # On failure, returns an `error` object that describes the error.
    def finalize!
        return finalize_tournament(self)
    end

    # If `current_match` is set, returns the `Match` object that corresponds
    # to that match.  Otherwise, returns `nil`.
    def current_match_obj
        return matches.find_by(id: current_match) if current_match.present?
    end

    # Stores the ID of the given Match in the Tournament table, and sends a
    # Slack notification if they are turned on for this Tournament.
    def set_current_match(match)
        match.start
        current_match_obj&.stop
        update(current_match: match.id)

        if send_slack_notifications && slack_notifications_channel.present?
            TournamentsHelper.notify_match_starting(self, match,
                                                    matches.upcoming.first)
        end
    end

    # Stores the names and scores of the given Match in the Tournament table, so
    # the TournamentViewer actions can return them until the next match begins.
    # Also sends a Slack notification if they are turned on for this Tournament.
    def set_match_complete(match)
        update(current_match: nil,
               view_gold_name: match.team_name(:gold, use_alt: true),
               view_blue_name: match.team_name(:blue, use_alt: true),
               view_gold_score: match.team_score(:gold),
               view_blue_score: match.team_score(:blue))

        if send_slack_notifications && slack_notifications_channel.present?
            TournamentsHelper.notify_match_complete(self, match)
        end
    end

    # Assigns group names to matches that are in a group stage.  This may not be
    # perfect; see the comments below for more info.
    # This should be called every time the Tournament's properties are re-read
    # from Challonge.
    def update_group_names
        # Clear the group names of matches that aren't in a group.
        matches.not_in_group.each(&:set_no_group_name)

        # Group names aren't exposed through the API, so we have to determine
        # the names ourselves.  Challonge appears to assign IDs that are consecutive
        # numbers (although we don't depend on them being consecutive), and then
        # names the groups in ascending order starting with "A".
        next_group_name = "A"

        group_names = matches.distinct.where.not(group_id: nil).
                        order(group_id: :asc).pluck(:group_id).
                        each_with_object({}) do |id, names|
            names[id] = next_group_name
            next_group_name = next_group_name.succ
        end

        group_names.each do |id, name|
            matches.group_is(id).each { |m| m.set_group_name(name) }
        end
    end

    # Sets alternate names for teams in this tournament.
    # `alt_names` is a hash where the keys are database IDs of teams, and the
    # values are the teams' alt names.  A value may be `nil` or an empty string
    # to mean that no alt name should be used for that team.
    def set_team_alt_names(alt_names)
        # Bail out if no names were passed.  This will usually happen only
        # during tests.
        return true if alt_names.blank?

        # Store each team's alternate name.  Any validation errors are copied
        # to our `errors` object.
        alt_names.each do |tid, alt_name|
            team = teams.find(tid)

            if !team.set_alt_name(alt_name.presence)
                team.errors.each { |field, msg| errors[field] << msg }
            end
        end

        return errors.empty?
    end

    # Returns the Tournament's state as a string that is suitable for use in the UI.
    # If the state is "underway", the string also shows the percentage of matches
    # that have been completed.
    def state_name
        if state != "underway"
            ActiveSupport::Inflector.humanize(state, capitalize: false)
        else
            I18n.t("tournaments.state_underway", progress: progress_meter)
        end
    end

    # Returns the color of the cabinet on the given side.  This string is suitable
    # for use in the UI.
    # `side` can be `:left` or `:right`.
    def cabinet_color(side)
        validate_param(side, SYMBOLS_LR)

        string_id = case side
                        when :left
                            gold_on_left ? :gold_cab_name : :blue_cab_name
                        when :right
                            gold_on_left ? :blue_cab_name : :gold_cab_name
                    end

        return I18n.t(string_id)
    end

    # Returns the color of the cabinet on the given side.  If `prefix` is passed,
    # that string is prepended to the color.
    # This string is *not* suitable for use in the UI, since it is never
    # translated.  It should be used only for internal identifiers.
    # `side` can be `:left` or `:right`.
    def cabinet_color_invariant(side, prefix = "")
        validate_param(side, SYMBOLS_LR)

        return prefix + case side
                            when :left
                                gold_on_left ? "gold" : "blue"
                            when :right
                                gold_on_left ? "blue" : "gold"
                        end
    end

    private

    def validate_datetimes
        # We allow `started_at` to be a few seconds into the future because of
        # the quick start demo feature.  The demo tournament is created and
        # then started immediately.  If the Challonge server's clock is slightly
        # ahead of the local clock, this validation will fail unless we allow
        # for a few seconds of slop.
        if started_at.present? && started_at > 5.seconds.from_now
            errors.add(:started_at, "cannot be in the future")
        end
    end
end

app/helpers/tournaments_helper.rb
# frozen_string_literal: true

module TournamentsHelper
    # Sends a message to Slack that announces the start of a match, and
    # optionally, the teams in the next match.
    def self.notify_match_starting(tournament, match, next_match = nil)
        msg = get_match_starting_msg(tournament, match, next_match)
        notify_slack(msg, tournament.slack_notifications_channel)
    end

    # Sends a message to Slack that announces the end of a match.
    def self.notify_match_complete(tournament, match)
        msg = get_match_complete_msg(tournament, match)
        notify_slack(msg, tournament.slack_notifications_channel)
    end

    # Builds the string that announces the start of a match.
    def self.get_match_starting_msg(tournament, match, next_match)
        msg = I18n.t("slack.match_starting", tournament_name: tournament.name,
                     match_number: match.number, left_team: match.team_name(:left),
                     right_team: match.team_name(:right))

        if next_match
            left_team_name = next_match.team_name(:left)
            right_team_name = next_match.team_name(:right)

            # If both team names are `nil`, then don't show the on-deck match
            # message.  This happens for the first match of the finals in a
            # double-elimination tournament.
            if left_team_name || right_team_name
                # If one team is TBD, always show that one second.
                first_team_name = left_team_name || right_team_name
                second_team_name = left_team_name.nil? ? nil : right_team_name
                second_team_name ||= I18n.t("slack.tbd")

                msg << I18n.t("slack.on_deck_match", first_team: first_team_name,
                              second_team: second_team_name)
            end
        end

        return msg
    end

    # Builds the string that announces the end of a match.
    def self.get_match_complete_msg(tournament, match)
        return I18n.t("slack.match_complete", tournament_name: tournament.name,
                      winning_team: match.team_name(:winner),
                      losing_team: match.team_name(:loser),
                      winning_score: match.team_score(:winner),
                      losing_score: match.team_score(:loser))
    end

    # Sends a message to a Slack channel asynchronously.
    def self.notify_slack(msg, channel_name)
        NotifySlackJob.perform_later(msg, channel_name)
    end
end

app/views/tournaments/_current_match.html.erb
<% match = current_match
   left_team = match.get_team(:left)
   right_team = match.get_team(:right)
   left_name = left_team.name
   right_name = right_team.name
   left_score = match.team_score(:left)
   right_score = match.team_score(:right)
   left_color = @tournament.cabinet_color(:left)
   right_color = @tournament.cabinet_color(:right) %>
<h1 class="curr_match_header">
<%= t(".header", number: match.number, round_name: match.round_name(capitalized: false)) %>
</h1>
<p>
<table>
<tbody>
  <tr>
    <td colspan='2' align="center"><h2 class="curr_match_color"><%= left_color %></h2></td>
    <td></td>
    <td colspan='2' align="center"><h2 class="curr_match_color"><%= right_color %></h2></td>
  </tr>
  <tr>
    <td><h1 class="curr_match_name"><%= left_name %></h1></td>
    <td><h1 class="curr_match_score"><%= left_score %></h1></td>
    <td align="center"><h1 class="curr_match_score">&mdash;</h1></td>
    <td align="right"><h1 class="curr_match_score"><%= right_score %></h1></td>
    <td align="right"><h1 class="curr_match_name"><%= right_name %></h1></td>
  </tr>
  <% if !@tournament.readonly? %>
    <tr>
      <td colspan='2'>
        <%= button_to t(".add_a_win"),
                      user_tournament_match_path(
                        @user, @tournament, match, left_score: left_score + 1,
                        right_score: right_score),
                      method: :put, form_class: :add_subtract_win_form,
                      title: t(".add_a_win_title") %>
        <%= button_to t(".subtract_a_win"),
                      user_tournament_match_path(
                        @user, @tournament, match, left_score: left_score - 1,
                        right_score: right_score),
                      method: :put, form_class: :add_subtract_win_form,
                      title: t(".subtract_a_win_title"),
                      disabled: left_score == 0 %>
        <p>
        <%= button_to t(".match_winner"),
                      user_tournament_match_path(
                        @user, @tournament, match, winner_id: match.get_team_id(:left)),
                      method: :put, title: t(".match_winner_title"),
                      disabled: left_score <= right_score %>
      </td>
      <td valign="top" align="center">
        <%= button_to t(".switch_sides"), [ :switch, @user, @tournament, match ] %>
      </td>
      <td colspan='2' align='right'>
        <%= button_to t(".add_a_win"),
                      user_tournament_match_path(
                        @user, @tournament, match, left_score: left_score,
                        right_score: right_score + 1),
                      method: :put, form_class: :add_subtract_win_form,
                      title: t(".add_a_win_title") %>
        <%= button_to t(".subtract_a_win"),
                      user_tournament_match_path(
                        @user, @tournament, match, left_score: left_score,
                        right_score: right_score - 1),
                      method: :put, form_class: :add_subtract_win_form,
                      title: t(".subtract_a_win_title"),
                      disabled: right_score == 0 %>
        <p>
        <%= button_to t(".match_winner"),
                      user_tournament_match_path(
                        @user, @tournament, match, winner_id: match.get_team_id(:right)),
                      method: :put, title: t(".match_winner_title"),
                      disabled: right_score <= left_score %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td colspan='2' valign="top">
    <% if !@tournament.readonly? %>
      <br>
    <% end %>
      <%= render partial: "tournaments/previous_matches", locals: { team: left_team } %>
    </td>
    <td></td>
    <td></td>
    <td valign="top" style="float:right">
    <% if !@tournament.readonly? %>
      <br>
    <% end %>
      <%= render partial: "tournaments/previous_matches", locals: { team: right_team } %>
    </td>
  </tr>
</tbody>
</table>
</p>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true, url: [tournament.user, tournament]) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= t(".errors_list_header", count: tournament.errors.count) %></h2>
      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.check_box :gold_on_left, id: :tournament_gold_on_left, autofocus: true %>
    <%= form.label :gold_on_left, t(".gold_on_left_html"),
                   for: :tournament_gold_on_left, accesskey: t(".gold_on_left_accesskey") %>
  </div>

  <div class="field">
    <%= form.check_box :send_slack_notifications, id: :tournament_send_slack_notifications %>
    <%= form.label :send_slack_notifications, t(".send_slack_notifications_html"),
                   for: :tournament_send_slack_notifications,
                   accesskey: t(".send_slack_notifications_accesskey") %>
  </div>

  <div class="field">
    <%= form.label :slack_notifications_channel, t(".slack_notifications_channel_html"),
                   for: :tournament_slack_notifications_channel,
                   accesskey: t(".slack_notifications_channel_accesskey") %>
    <%= form.text_field :slack_notifications_channel,
                        id: :tournament_slack_notifications_channel %>
  </div>
  <hr>
  <h3><%= t(".alt_names_header") %></h3>
  <p><%= t(".alt_names_instructions_html") %></p>
  <table id="alt_team_names_table">
    <thead>
      <tr>
        <th><%= t(".alt_names_th_name") %></th>
        <th><%= t(".alt_names_th_alt_name") %></th>
      </tr>
    </thead>
    <tbody>
      <% tournament.teams.sort_by(&:name).each do |team| %>
        <tr>
          <td id='<%= "team_name_#{team.id}" %>'><%= team.name %></td>
          <td>
            <%= text_field_tag "team_alt_names[]", team.alt_name, id: "alt_name_#{team.id}" %>
            <%= hidden_field_tag "team_ids[]", team.id, id: "team_id_#{team.id}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <p class="actions">
    <%= form.submit %>
  </p>
<% end %>

app/views/tournaments/_match_list.html.erb
<% show_actions = !(readonly || match_list.all?(&:complete?) || match_list.all?(&:teams_are_tbd?)) %>
<table id="<%= table_id %>">
<thead>
  <tr>
    <th><%= t(".match_number") %></th>
    <th><%= t(".round") %></th>
    <th><%= t(".teams") %></th>
    <% if show_actions %>
      <th><%= t(".actions") %></th>
    <% end %>
  </tr>
</thead>
<tbody>
  <% match_list.each do |m| %>
  <% if m.get_team_id(:left)
         left_team_name = m.team_name(:left)
         left_team_won = m.team_won?(:left)

         if m.complete?
             left_team_class = left_team_won ? "winning_team" : "losing_team"
         else
             left_team_class = "upcoming_team"
         end

         if !left_team_won && m.forfeited
             left_team_class << " forfeited_team"
         end
     else
         # In Swiss tournaments, future rounds have matches without any teams or
         # prereqs.  Skip those matches.
         match_num = m.tournament.matches.find_by_challonge_id(m.team_prereq_match_id(:left))&.number
         next unless match_num

         left_team_class = "tbd_team"

         if m.team_is_prereq_match_loser?(:left)
             left_team_name = t(".loser_of_match", number: match_num)
         else
             left_team_name = t(".winner_of_match", number: match_num)
         end
     end
  %>
  <% if m.get_team_id(:right)
         right_team_name = m.team_name(:right)
         right_team_won = m.team_won?(:right)

         if m.complete?
             right_team_class = right_team_won ? "winning_team" : "losing_team"
         else
             right_team_class = "upcoming_team"
         end

         if !right_team_won && m.forfeited
             right_team_class << " forfeited_team"
         end
     else
         match_num = m.tournament.matches.find_by_challonge_id(m.team_prereq_match_id(:right)).number
         right_team_class = "tbd_team"

         if m.team_is_prereq_match_loser?(:right)
             right_team_name = t(".loser_of_match", number: match_num)
         else
             right_team_name = t(".winner_of_match", number: match_num)
         end
     end
  %>
  <tr>
    <td><%= m.number %></td>
    <td><%= m.round_name %></td>
    <td>
      <% if m.complete? %>
        <span class="<%= left_team_class %>"><%= left_team_name %></span>
        <% if m.forfeited %>
          <% if !left_team_won %>
            <span class="forfeited_score"><%= t(".forfeited") %></span>
          <% end %>
        <% else %>
          &nbsp;<span class="<%= left_team_class %>"><%= m.team_score(:left) %></span>
        <% end %>
        &mdash;
        <% if m.forfeited %>
          <% if !right_team_won %>
            <span class="forfeited_score"><%= t(".forfeited") %></span>
          <% end %>
        <% else %>
          <span class="<%= right_team_class %>"><%= m.team_score(:right) %></span>&nbsp;
        <% end %>
        <span class="<%= right_team_class %>"><%= right_team_name %></span>
      <% else %>
        <span class="<%= left_team_class %>"><%= left_team_name %></span> &mdash;
        <span class="<%= right_team_class %>"><%= right_team_name %></span>
      <% end %>
    </td>
    <% if show_actions && !(m.complete? || m.teams_are_tbd?) %>
      <td>
        <%= link_to t(".start_this_match"), [ :start, @user, @tournament, m ], method: :post %> |
        <%= link_to t(".switch_sides"), [ :switch, @user, @tournament, m ], method: :post %>
      </td>
    <% end %>
  </tr>
  <% end %>
</tbody>
</table>

app/views/tournaments/_previous_matches.erb
<b><%= t(".header") %></b><br>
<% matches = team.tournament.matches.completed.has_team(team) %>
<%= t(".none") if matches.blank? %>
<% matches.each do |match| %>
  <% if match.team_won?(team) %>
    <% if match.forfeited %>
      <%= t(".match_won_forfeited", loser: match.team_name(:loser)) %>
    <% else %>
      <%= t(".match_won", loser: match.team_name(:loser),
            winning_score: match.team_score(:winner), losing_score: match.team_score(:loser)) %>
    <% end %>
  <% else %>
    <% if match.forfeited %>
      <%= t(".match_lost_forfeited", winner: match.team_name(:winner)) %>
    <% else %>
      <%= t(".match_lost", winner: match.team_name(:winner),
            winning_score: match.team_score(:winner), losing_score: match.team_score(:loser)) %>
    <% end %>
  <% end %>
  <br>
<% end %>

app/views/tournaments/edit.html.erb
<% content_for :title, t(".page_title", name: @tournament.name) %>
<h1><%= t(".page_header", name: @tournament.name) %></h1>
<p><%= render "form", tournament: @tournament %>
<p><%= link_to t("cancel_link"), :back %>

app/views/tournaments/index.html.erb
<% content_for :title, t(".page_title", user_name: @user.user_name) %>
<p id="notice"><%= notice %></p>
<h1><%= t(".page_header", user_name: @user.user_name) %></h1>
<p><%= t(".instructions1_html") %></p>
<p><%= t(".instructions2") %></p>
<p><%= t(".instructions3_html") %></p>

<% if @user.show_quick_start %>
<hr>
<div id='quick_start'>
<h3><%= t(".quick_start_header") %></h3>
<p><%= t(".quick_start_body_html") %></p>
<p>
<%= button_to t(".quick_start_button"), user_demo_path(@user), form_class: :quick_start_form %>
<%= button_to t(".hide_quick_start_button"), user_hidedemo_path(@user), form_class: :quick_start_form %>
</p>
</div>
<hr>
<% end %>

<% if @tournaments.present? %>
<p>
<table id='tournament_list'>
  <thead>
    <tr>
      <th><%= t(".name") %></th>
      <th><%= t(".state") %></th>
      <th><%= t(".actions") %></th>
      <th><%= t(".links") %></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr id="tournament<%= tournament.id %>">
        <td><%= tournament.subdomain.present? ? t(".name_with_subdomain", name: tournament.name, subdomain: tournament.subdomain) : tournament.name %></td>
        <td><%= tournament.state_name %></td>
        <td>
          <%= link_to t(".manage_tournament"), [ :refresh, @user, tournament ] %> |
          <%= link_to t("tournaments.edit_tournament"), [ :edit, @user, tournament ] %>
        </td>
        <td>
          <%= link_to t(".challonge"), tournament.challonge_url, target: :_blank %> |
          <%= link_to t(".spectator_view"), view_tournament_path(tournament.challonge_alphanumeric_id), target: :_blank %> |
          <%= link_to t(".kiosk"), tournament_kiosk_path(tournament.challonge_alphanumeric_id), target: :_blank %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>
<% end %>
<p>
<%= link_to t(".reload_tournaments"), refresh_user_tournaments_path(@user) %> |
<%= link_to t("users.edit_user"), edit_user_path(@user) %> |
<%= link_to t("users.log_out"), logout_path, method: :delete %>
</p>

app/views/tournaments/show.html.erb
<% content_for :title, @tournament.name %>
<% readonly = @tournament.readonly? %>
<% if !readonly %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1><%= @tournament.name %></h1>
<% if !readonly %>
  <p>Links: <%= link_to t(".bracket_link"), @tournament.challonge_url, target: :_blank %> |
     <%= link_to t(".spectator_view_link"), view_tournament_path(@tournament.challonge_alphanumeric_id), target: :_blank %> |
     <%= link_to t(".kiosk_link"), tournament_kiosk_path(@tournament.challonge_alphanumeric_id), target: :_blank %>
  </p>
<% end %>

<% if @current_match.present? %>
  <hr>
  <%= render partial: "tournaments/current_match", object: @current_match %>
<% end %>

<% if @upcoming_matches.present? %>
  <hr>
  <p><h2><%= t(".upcoming_matches") %></h2></p>
  <p><%= render partial: "tournaments/match_list", object: @upcoming_matches,
                locals: { table_id: "upcoming", readonly: readonly } %></p>
<% elsif @tournament.finalizable? %>
  <% if !readonly %>
    <hr>
    <h2><%= t(".finalize_tournament") %></h2>
    <p><%= t(".finalize_text_html") %></p>
    <p><%= button_to t(".finalize_tournament_button"),
                     finalize_user_tournament_path(@user, @tournament) %></p>
  <% end %>
<% elsif @tournament.complete? %>
  <hr>
  <h2><%= t(".final_standings") %></h2>
  <table>
    <thead>
      <tr>
        <th><%= t(".place") %></th>
        <th><%= t(".seed") %></th>
        <th><%= t(".name") %></th>
      </tr>
    </thead>
    <tbody>
      <% @teams_in_final_rank_order.each do |t| %>
        <tr>
          <td><%= t.final_rank %></td>
          <td><%= t.seed %></td>
          <td><%= t.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif @tournament.in_group_stage? %>
  <hr>
  <h2><%= t(".group_stage_end") %></h2>
  <% if readonly %>
    <p><%= t(".group_stage_end_text_readonly") %></p>
  <% else %>
    <p><%= t(".group_stage_end_text_html", bracket_url: @tournament.challonge_url,
             refresh_url: refresh_user_tournament_path(@user, @tournament)) %></p>
  <% end %>
<% end %>

<% if @completed_matches.present? %>
  <hr>
  <p><h2><%= t(".completed_matches") %></h2>
  <p><%= render partial: "tournaments/match_list", object: @completed_matches,
                locals: { table_id: "completed", readonly: readonly } %></p>
<% end %>

<hr>
<p><h2><%= t(".team_records") %></h2>
<table id='team_records'>
  <thead>
    <tr>
      <th><%= t(".seed") %></th>
      <th><%= t(".record") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teams_in_seed_order.each do |t| %>
      <% num_wins = @tournament.matches.winner_is(t).count
         num_losses = @tournament.matches.loser_is(t).count
      %>
      <tr>
        <td><%= t.seed %></td>
        <td><%= t(".team_record", name: t.name, wins: num_wins, losses: num_losses) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>

<% if !readonly %>
  <hr>
  <%= link_to t(".reload"), [ :refresh, @user, @tournament ] %> |
  <%= link_to t("tournaments.edit_tournament"), [ :edit, @user, @tournament ] %> |
  <%= link_to t(".tournament_list"), user_tournaments_path(@user) %> |
  <%= link_to t("user.log_out"), logout_path, method: :delete %>
<% end %>